"""`kin ask` option sets shared by the answer tests.

F25 is the default configuration. Tests of one reading rule start from the
pre-F25 baseline, where every F25 option is off, and turn on what they test,
so each option's own effect stays isolated.
"""

# The default `ask:` configuration (F25), as measured.
F25_ASK = {
    'hard_effort': 'high',
    'dialogue_effort': 'xhigh',
    'dialogue_plan': True,
    'reread': True,
    'max_input_tokens': 20000,
    'details': True,
    'recall_only': True,
    'timeline_facets': True,
    'episode_scope': True,
    'dialogue_focus': True,
    'inference_candidates': True,
    'date_anchors': True,
    'count_scope': True,
    'count_readings': True,
    'predicate_counts': True,
    'quantity_readings': True,
    'window_readings': True,
    'relative_focus': True,
    'event_reference': True,
    'subject_scope': True,
    'approximate_state': True,
    'exchange_context': True,
    'window_search': True,
    'fact_tiers': 40,
    'dialogue_context_tokens': 14000,
    'list_position': True,
    'component_updates': True,
    'remainder_quantities': True,
    'recall_candidates': True,
    'archival_time': True,
    'disposition_inference': True,
    'large_effort': 'xhigh',
    'large_landmarks': True,
    'large_recall_exchange': True,
    'large_response_contract': True,
    'ordering_witnesses': True,
    'dialogue_fields': True,
    'episode_endpoints': True,
    'fixed_clock': True,
    'large_span_witnesses': True,
    'large_claim_witnesses': True,
    'large_summary_coverage': True,
    'witness_coverage': True,
    'count_witnesses': True,
    'coarse_ordering': True,
    'ordering_occurrences': True,
    'large_evidence_pack': True,
    'large_evidence_pack_intents': 'aggregation,assistant_recall',
    'archive_clock': True,
    'dialogue_episode_bindings': True,
    'dialogue_instance_identity': True,
    'count_example_membership': True,
    'large_claim_scan': True,
    'large_summary_methods': True,
}

# The F25 options at their previous (off) values.
PRE_F25_ASK = {
    'hard_effort': '',
    'dialogue_effort': '',
    'dialogue_plan': False,
    'reread': False,
    'max_input_tokens': 0,
    'details': False,
    'recall_only': False,
    'timeline_facets': False,
    'episode_scope': False,
    'dialogue_focus': False,
    'inference_candidates': False,
    'date_anchors': False,
    'count_scope': False,
    'count_readings': False,
    'predicate_counts': False,
    'quantity_readings': False,
    'window_readings': False,
    'relative_focus': False,
    'event_reference': False,
    'subject_scope': False,
    'approximate_state': False,
    'exchange_context': False,
    'window_search': False,
    'fact_tiers': 0,
    'dialogue_context_tokens': 0,
    'list_position': False,
    'component_updates': False,
    'remainder_quantities': False,
    'recall_candidates': False,
    'archival_time': False,
    'disposition_inference': False,
    'large_effort': '',
    'large_landmarks': False,
    'large_recall_exchange': False,
    'large_response_contract': False,
    'ordering_witnesses': False,
    'dialogue_fields': False,
    'episode_endpoints': False,
    'fixed_clock': False,
    'large_span_witnesses': False,
    'large_claim_witnesses': False,
    'large_summary_coverage': False,
    'witness_coverage': False,
    'count_witnesses': False,
    'coarse_ordering': False,
    'ordering_occurrences': False,
    'large_evidence_pack': False,
    'large_evidence_pack_intents': '',
    'archive_clock': False,
    'dialogue_episode_bindings': False,
    'dialogue_instance_identity': False,
    'count_example_membership': False,
    'large_claim_scan': False,
    'large_summary_methods': False,
}
