"""Smoke tests for src/kindex/adapters/github.py (auto-generated by pact adopt)."""

import pytest

def test_import_kindex_adapters_github():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("kindex.adapters.github")
    assert mod is not None

def test_is_gh_available_is_callable():
    """Function is_gh_available exists and is callable."""
    import importlib
    mod = importlib.import_module("kindex.adapters.github")
    fn = getattr(mod, "is_gh_available", None)
    assert fn is not None, "'is_gh_available' not found in kindex.adapters.github"
    assert callable(fn)

def test_ingest_issues_is_callable():
    """Function ingest_issues exists and is callable."""
    import importlib
    mod = importlib.import_module("kindex.adapters.github")
    fn = getattr(mod, "ingest_issues", None)
    assert fn is not None, "'ingest_issues' not found in kindex.adapters.github"
    assert callable(fn)

def test_ingest_prs_is_callable():
    """Function ingest_prs exists and is callable."""
    import importlib
    mod = importlib.import_module("kindex.adapters.github")
    fn = getattr(mod, "ingest_prs", None)
    assert fn is not None, "'ingest_prs' not found in kindex.adapters.github"
    assert callable(fn)

def test_ingest_commits_is_callable():
    """Function ingest_commits exists and is callable."""
    import importlib
    mod = importlib.import_module("kindex.adapters.github")
    fn = getattr(mod, "ingest_commits", None)
    assert fn is not None, "'ingest_commits' not found in kindex.adapters.github"
    assert callable(fn)
