"""Smoke tests for src/kindex/adapters/base.py (auto-generated by pact adopt)."""

import pytest

def test_import_kindex_adapters_base():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("kindex.adapters.base")
    assert mod is not None
