"""Smoke tests for src/kindex/adapters/projects.py (auto-generated by pact adopt)."""

import pytest

def test_import_kindex_adapters_projects():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("kindex.adapters.projects")
    assert mod is not None
