"""Smoke tests for src/kindex/store.py (auto-generated by pact adopt)."""

import pytest

def test_import_kindex_store():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("kindex.store")
    assert mod is not None
