"""Smoke tests for src/kindex/budget.py (auto-generated by pact adopt)."""

import pytest

def test_import_kindex_budget():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("kindex.budget")
    assert mod is not None
